### PR TITLE
feat: show safe mode alert when tapping status bar

### PR DESCRIPTION
**Pull request by iCrazeiOS**
discussed in #43

### CODE REVIEW

**Comment by tale** [comment]
@iCrazeiOS can we make this show an indicator in the status bar? Like how substrate itself does.

**Comment by tale** [comment]
Maybe some kind of alert icon then? Just something to indicate that it's actually tappable and can do something.

**Comment by evelyneee** [comment]
Can something like the blue location pill be added, just make it red? If you use the right objc methods it’ll work on all devices

**Comment by evelyneee** [comment]
IMG_0771
This

**Comment by iCrazeiOS** [comment]
IMG_3399

Tested on a notched device (11 Pro) and non-notched (6S).

Test has failed, but that's because of some Procursus issue, not due to this commit 🙃

**Review by dhinakg — APPROVED** [review]

**Review by Sooooo7 — COMMENTED** [review]
C

**Pull request merged**
